### ISSUE TITLE
G2 crash

### ISSUE THREAD

**Issue by tomedi** [REGoth-project/REGoth#194] opened 2017-06-12 09:40 UTC
The latest AsyncWorldInit causes a crash at a certain Point: Startup scripts. 
![crash](https://user-images.githubusercontent.com/13464019/27028076-fba1e2de-4f63-11e7-89cd-9c435f325571.png)

**Comment by tomedi** [comment] 2017-06-12 09:42
G1 starts.

**Comment by markusobi** [comment] 2017-06-12 10:13
This should be fixed on the latest commit, but the build-server didn't build the latest commits (problem with submodule). When the build-issue is fixed, this should be resolved.

**Comment by tomedi** [comment] 2017-06-12 10:26
Ok! I'm going to check the latest build when it's done.

**Comment by markusobi** [comment] 2017-06-12 12:27
There were some problems with the bgfx command queue overflowing, but this issue was not present in 0.3.256.
@tomedi which version did you use? 0.3.256?

 0.3.256 works fine for me using g1/g2.

I had some infrequent crashes on linux tesing g1/g2, but I couldn't reproduce them. The game crashed when rendering the BarView, so it might be related to the loading bar.

**Comment by tomedi** [comment] 2017-06-12 12:48
Well, I tested 0.3.263 as well, the crash occurs again! This time at this point: 
![crash_2](https://user-images.githubusercontent.com/13464019/27034487-327af34e-4f7e-11e7-8666-9061326b13a9.png)

**Comment by markusobi** [comment] 2017-06-12 13:59
please try with hud disabled:
- close main-menu before starting new game
- open console and disable hud via console command `hud`
- close console
- open menu again (is invisible)
- hit enter (blindly selects new game)

**Comment by tomedi** [comment] 2017-06-12 14:07
Just tested again: crash only occurs at newworld.zen!

**Comment by tomedi** [comment] 2017-06-12 14:22
Did the thing according to your plan! Again a crash- this time at that point: 
![crash_3](https://user-images.githubusercontent.com/13464019/27038434-4a2dfbc8-4f8b-11e7-91e2-06455c001a2b.png)

**Comment by tomedi** [comment] 2017-06-12 14:57
I'm very sorry, also the latest version (0.3.264) doesn't do it... Here's the log: 
![crash_4](https://user-images.githubusercontent.com/13464019/27040064-2ec9b20a-4f90-11e7-92b4-96499b38da57.png)

**Comment by tomedi** [comment] 2017-06-12 14:59
The weird thing is, that without the hud, it crashes at a different point: 
![crash_5](https://user-images.githubusercontent.com/13464019/27040161-77b4d54e-4f90-11e7-802a-00b3ed948cb8.png)

**Comment by degenerated1123** [comment] 2017-06-12 21:54
Probably because it's doing asynchronous loading. A crash dump would be helpful, but we don't have anything that would write one right now...

**Comment by tomedi** [comment] 2017-06-13 08:46
@degenerated1123 I tried to debug, but I got this error message:
>*** ERROR: Module load completed but symbols could not be loaded for REGoth.exe

What can I do?

**Comment by degenerated1123** [comment] 2017-06-13 17:15
There are no debug-information linked into the .exe-files from AppVeyor, so there isn't much that you can do

**Comment by tomedi** [comment] 2017-06-13 20:42
Oh, that's unfortunate! Btw, latest build is also crashing... (0.3.265)

**Comment by markusobi** [comment] 2017-06-14 17:19
I experienced some crashes too while "Running startup scripts".
Callstack was:
```
bgfx::getAvailTransientVertexBuffer
View::screenQuad
View::drawTexture
ImageView::update
LoadingScreen::update
```
[bgfx::getAvailTransientVertexBuffer#line 2908](https://github.com/bkaradzic/bgfx/blob/ed4c70631b4c2086ed990dd5a20fd87e67e7699a/src/bgfx.cpp#L2908)
`_decl.m_stride` was `16` at the time I looked at it in the debugger

I remember that I also had some crashes in `BarView::update` the corresponding object was the Manabar (I checked the x/y coordinates)

**Comment by markusobi** [comment] 2017-06-14 19:04
I pushed `startup_<worldname>` and `init_<worldname>` to the Mainthread (sledgehammer approach, will cause the loading screen to hang for a short time).
@tomedi try [nightly-0.3.268](https://github.com/REGoth-project/REGoth/releases/)

**Comment by tomedi** [comment] 2017-06-14 21:36
@markusobi I did! Crash again. This time at that point: 
![crash_6](https://user-images.githubusercontent.com/13464019/27155733-5522e3a6-515a-11e7-8864-da8047ccbfe5.png)

**Comment by tomedi** [comment] 2017-06-15 12:02
Crash at 0.3.269: 
![crash_7](https://user-images.githubusercontent.com/13464019/27180329-3bbc70a2-51d3-11e7-9562-64723eb5fac3.png)

**Comment by markusobi** [comment] 2017-06-15 16:46
@tomedi can you find the last version, that worked for you?

**Comment by tomedi** [comment] 2017-06-15 18:59
@markusobi Sure, np!

**Comment by tomedi** [comment] 2017-06-15 19:18
@markusobi The only AsyncLoadInit- build that works on my laptop is the first one (0.3.249) :/

**Comment by tomedi** [comment] 2017-06-15 19:46
I dug deeper. The builds between 0.3.249 and 0.3.256 were all crashing. 0.3.254 was able to load oldworld.zen, whereas 0.3.256 and after, every build was able to load old- and addonworld, but never newworld.zen. Hope that I was able to help...

**Comment by tomedi** [comment] 2017-06-19 14:49
The crash could be reproduced. It was an error that occured on internal graphic cards.

**Closed** 2017-06-19 18:36 UTC
