### ISSUE TITLE
[G1] Texture Bugs 

### ISSUE THREAD

**Issue by Fragy** [REGoth-project/REGoth#148] opened 2017-02-25 19:18 UTC
On Places like shown on the Picture are some Strange looking Textures. Build: nightly-0.3.41
![gothic texture bug](https://cloud.githubusercontent.com/assets/26026536/23334057/6e2f6a2c-fb97-11e6-8552-3bf404429c4b.jpg)

Heres another Example Nice Fire :) but Ugly Stone Texture. Build: nightly-0.3.41
![gothic texture bug 2](https://cloud.githubusercontent.com/assets/26026536/23334167/c0092958-fb99-11e6-8174-1c58c9674678.jpg)

Some more Strange Textures. Build: nightly-0.3.45
![gothic texture bug 3](https://cloud.githubusercontent.com/assets/26026536/23339550/92f17556-fc25-11e6-9c7b-f1e9fde2a9ee.jpg)

Build: nightly-0.3.45
![gothic texture bug 4](https://cloud.githubusercontent.com/assets/26026536/23339555/a4f8376c-fc25-11e6-9ce3-1c05327f1ca7.jpg)

Build: nightly-0.3.45
![gothic texture bug 5](https://cloud.githubusercontent.com/assets/26026536/23339557/afdd48ac-fc25-11e6-9e69-49d2353621df.jpg)

Build: nightly-0.3.45
![gothic texture bug 6](https://cloud.githubusercontent.com/assets/26026536/23339559/b886eee0-fc25-11e6-82bf-6e25e98dfc0e.jpg)

Build: nightly-0.3.45
![gothic texture bug 7](https://cloud.githubusercontent.com/assets/26026536/23339561/c44365ce-fc25-11e6-8e8c-14470f1cd095.jpg)

Build: nightly-0.3.45
![gothic texture bug 8](https://cloud.githubusercontent.com/assets/26026536/23339563/d12975f8-fc25-11e6-9591-66fa6cf13c75.jpg)

Build: nightly-0.3.45
![gothic texture bug 9](https://cloud.githubusercontent.com/assets/26026536/23339566/db45b8b2-fc25-11e6-9969-8705c9a1bac1.jpg)

Build: nightly-0.3.45
![gothic texture bug 10](https://cloud.githubusercontent.com/assets/26026536/23339568/e654a074-fc25-11e6-825b-20bd093c6c53.jpg)

Build: nightly-0.3.45
![gothic texture bug 11](https://cloud.githubusercontent.com/assets/26026536/23339570/eef54fe4-fc25-11e6-88e2-bfdf05231a5c.jpg)

**Comment by Fragy** [comment] 2017-02-26 12:25
Updated with some new Screens from nightly-0.3.45 ! I think thats most of the ugly Textures maybe I find some more 🗡

**Comment by degenerated1123** [comment] 2017-02-26 12:30
Please always check if those isntances of bad texturing doesn't happen in the original as well. Also, I don't think you need to find more. Seems more like all of them are caused by the same code-issue and they should all go away if we fix it.

Probably because if the indexing-algorithm doing more than it should...
By the way, you can set the current time to be daytime again by pressing F10 and typing `set clock 8 0`.

**Comment by Fragy** [comment] 2017-02-26 13:51
These Bugs are in the Original Gothic 1 too. Maybe Bad Texture placement i dont know the game was original Developed for a 4:3 - 640x480 resolution thats why you get the best expirence in the game with the cameras, text and inventory scaling when you play the game on this resolution without a mouse everything above 640x480 is streched and the Fov is not not right. 1280x960 is 2x the resolution and the aspect ratio is still good even on a 16:9 Screen.

**Comment by degenerated1123** [comment] 2017-02-26 14:07
These stretched textures on the worldmesh have nothing to do with the used resolution. It's just bad UV-mapping, mostly in places where they thought nobody would care or look anyways. Unfortunately, there's nothing we can do about that in REGoth. Someone could fix those issues in a 3D-Program though.

**Comment by Fragy** [comment] 2017-02-26 14:12
Ok Gothic Reloaded Mod with your dx11 renderer is very good looking maybe they can Merge with REGoth the swampcamp looks so nice.

**Comment by jangernert** [comment] 2017-02-26 17:47
Most of the places you used as an example are (nearly) unreachable in the original game. So of course there was no need for PB to put hours of work into places like this.
Yes, as soon as REGoth matures a bit more we are going to try to run it with the GRM assets. We had to patch the original game a lot to get all our assets in the engine, and still some people are reporting issues. All this will hopefully be a lot easier with REGoth. Not even speaking of the Linux support :)
(I'm EvilTwin from WoG, one of the 3D guys of the GRM)

**Comment by Fragy** [comment] 2017-02-26 22:19
Heres something thats not good too "Missing textures". Its in the Original Gothic too.
![gothic texture bug 12](https://cloud.githubusercontent.com/assets/26026536/23344284/fa8fc7d6-fc79-11e6-969f-ded8975f587e.jpg)

**Comment by jangernert** [comment] 2017-02-26 22:21
All this has NOTHING to do with this project =/

**Comment by degenerated1123** [comment] 2017-02-26 22:25
I think the issue in the very first picture could have been caused by our loader. I do believe someone telling me that particular one wasn't in the original game.

As @jangernert said, everything mesh, texture or content-related in general that is in the original should not be fixed by REGoth, but rather by a patch for the original game, which REGoth then can load as well.

@jangernert Oh, I didn't know you were EvilTwin! Hello, I guess! :smile:

**Comment by Fragy** [comment] 2017-02-26 22:41
It's there but when you swim closer it dissapears and the right texture is been loaded i use gog version of gothic1 and II.
Texture Bad
![gothic orig texture bug](https://cloud.githubusercontent.com/assets/26026536/23344443/de00a1f0-fc7c-11e6-8f90-f4fc1bf1a192.jpg)
Texture Good
![gothic orig texture bug 2](https://cloud.githubusercontent.com/assets/26026536/23344449/f617da06-fc7c-11e6-8864-aaf7634efe9e.jpg)

**Closed** 2017-04-28 13:55 UTC
Labels: invalid
