### ISSUE TITLE
Fn key command causes crash

### ISSUE THREAD

**Issue by tomedi** [REGoth-project/REGoth#85] opened 2017-01-20 14:09 UTC
When you are using the FN- key whilst running REGoth (for example you want to turn the sound louder), it causes a crash.

**Comment by jangernert** [comment] 2017-01-20 14:27
Most likely duplicate of #74

**Comment by astillich** [comment] 2017-01-22 21:46
Should be fixed with the 'Configfiles' PR

**Closed by astillich** 2017-01-22 21:46 UTC
