### ISSUE TITLE
Bodies are not showing 

### ISSUE THREAD

**Issue by DeDudek** [REGoth-project/REGoth#372] opened 2019-04-10 15:14 UTC
![Screenshot_20190410-171221](https://user-images.githubusercontent.com/49489249/55891013-179e4500-5bb4-11e9-98d4-4021cd77fb62.jpg)

is this possible to fix this? my phone is HUAWEI Y6

**Comment by ChaosMarc** [comment] 2019-04-11 05:36
this is a duplicate of #305 so I guess at the moment there is no way to fix it.

**Comment by ataulien** [comment] 2019-04-11 05:44
@ChaosMarc is right, this is a known issue. It even says so in the last official release for android: https://github.com/REGoth-project/REGoth/releases/tag/0.4-android

**Closed by ataulien** 2019-04-11 05:44 UTC
